apiVersion : networking.k8s.io/v1
kind: Ingress
metadata: 
  name: ingress-hosts

spec:
  rules: 
  - host: nginx.io
    http:
      paths:
        - backend:
           serviceName: as-deployment
           servicePort: 80
  - host: as.nginx.io
    http:
      paths:
        - backend:
           serviceName: main-deploymen
           servicePort: 8080 